### ISSUE TITLE
Latest vscode is not compatible

### ISSUE THREAD

**Issue by renews** [diegoulloao/neofusion.vscode#1]
Cant install it on the latest vscode.
Very nice theme btw, I use everywhere haha.

**Comment by diegoulloao** [comment]
> Cant install it on the latest vscode. Very nice theme btw, I use everywhere haha.

It's working for me.
Hey, glad. you like it!

```
Version: 1.93.1 (Universal)
Commit: 38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40
Date: 2024-09-11T17:20:05.685Z
Electron: 30.4.0
ElectronBuildId: 10073054
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Darwin arm64 24.0.0
```

Could you share more details about your version?

Did you try reloading vscode or re installing the theme?

**Comment by renews** [comment]
I gues im not on the latest... can you add support to this version too? I cant update to 1.93.1.

Sorry about the wrong report.

![CleanShot 2024-10-01 at 10 30 18@2x](https://github.com/user-attachments/assets/63e06ab3-81ee-4afd-a424-2c4b85b15c2d)

**Comment by diegoulloao** [comment]
> I gues im not on the latest... can you add support to this version too? I cant update to 1.93.1.
> 
> Sorry about the wrong report.
> 
> ![CleanShot 2024-10-01 at 10 30 18@2x](https://private-user-images.githubusercontent.com/53726/372384208-63e06ab3-81ee-4afd-a424-2c4b85b15c2d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwNDQ5ODcsIm5iZiI6MTczMDA0NDY4NywicGF0aCI6Ii81MzcyNi8zNzIzODQyMDgtNjNlMDZhYjMtODFlZS00YWZkLWE0MjQtMmM0Yjg1YjE1YzJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI3VDE1NTgwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThhODg0ZDE5MGQwMDc0MTEwNTQyNWVjZWMwY2MyNWM0YmQxNjcyMzU5NTNmOTE2ZmFhZTZlMTU0ZTJjM2I0YzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.V3mEEUEQo1SxNVAHMg6m4LLM1OYhqQSlD3xcW34SOzo)

@renews sorry for the delay, work has been pretty stressful lately.
Were you able to fix it?

**Comment by renews** [comment]
yeah it work nw, thx!
